### ISSUE TITLE
can not run the code

### ISSUE THREAD

**Issue by commatrixs** [nobuyuki83/accurate_bc_for_mls_mpm#1]
thanks for your sharing! It is a good learning material of mpm boundary condition. But i can not run it. It seems some necessary files are missing.Could you please upload additional files?

**Comment by nobuyuki83** [comment]
Can you tell me what file is missing? Is it source code or input file?

**Comment by commatrixs** [comment]
Dear nobuyuki,

it can work. i am sorry about my mistake. Thanks for your sharing!

**Comment by nobuyuki83** [comment]
Cool! Enjoy!!
